CREATE TABLE IF NOT EXISTS camp_media_likes (
    LikeId INT AUTO_INCREMENT PRIMARY KEY,
    MediaId INT NOT NULL,
    UserId INT NOT NULL,
    LikedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MediaId) REFERENCES camp_media(MediaId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES users(UserId) ON DELETE CASCADE,
    UNIQUE KEY unique_media_user_like (MediaId, UserId)
);

CREATE TABLE IF NOT EXISTS camp_media_comments (
    CommentId INT AUTO_INCREMENT PRIMARY KEY,
    MediaId INT NOT NULL,
    UserId INT NOT NULL,
    CommentText TEXT NOT NULL,
    IsDeleted BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MediaId) REFERENCES camp_media(MediaId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES users(UserId) ON DELETE CASCADE
);
